server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: wishlist-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/wishlist
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
